### ISSUE TITLE
Speaker selection and training on full VCTK set

### ISSUE THREAD

**Issue by skol101** [yl4579/StarGANv2-VC#33]
Hello, is there any particular reason to select just 20 and only those specific speakers? 

Have you trained on the full VCTK dataset and if so, have results been similar to training on 20 speakers only?

**Comment by yl4579** [comment]
The reason for choosing those 20 speakers was stated in the paper, it was because "For a fair comparison, we train both the baseline model and our framework on the same 20 selected speakers reported in [18] from VCTK dataset [19]." The source was also commented on the [example Jupyter notebook for inference](https://github.com/yl4579/StarGANv2-VC/blob/main/Data/VCTK.ipynb). There's no limit on how many speakers you can use in general, but the more speakers the more discriminative power you will need to get a good result because we have no text labels in our dataset. That is to say, if you want to train on like 100 speakers, you may need 5 discriminators each for 20 speakers. See #6 for more details, we have very great discussions about it there.
