### ISSUE TITLE
 Is there any guidance on distributed? 

### ISSUE THREAD

**Issue by 980202006** [yl4579/StarGANv2-VC#4]
When I run the DataParallel mode on a single machine with multiple cards, I encountered a lot of problems

**Comment by yl4579** [comment]
The key is to turn off the mixed-precision training by setting `fp16_run` to false in `config.yml`, and most errors will go away. However, this makes training much slower and takes a lot more RAM and it is not necessary to train our model. A single GTX 1080 Ti should do the job with the default configurations.

**Comment by 980202006** [comment]
What an amazing code.
In practice, I found that GPU resource occupation increases with the increase of domain. Is there a solution for thousands of speakers?
Even with 4 GPUs, the model cannot be trained with a batch size of 5.

**Comment by yl4579** [comment]
Since the original StarGAN v2 wasn't designed to take thousands of domains, you will need to find a way to work around it. The reason RAM consumption increases with the number of domains is that in [model.py](https://github.com/yl4579/StarGANv2-VC/blob/main/models.py#L253), the unshared components of the mapping network consist of individual small subnetworks dedicated to each domain, so is the style encoder. You may remove the mapping network completely, for example. The style encoder can also be changed for zero-shot conversion, though more studies need to be done because what I got so far was not very ideal. You may want to open a new issue to discuss how to make it work with thousands of speakers or zero-shot in general.

**Comment by 980202006** [comment]
thank you!

**Comment by skol101** [comment]
With batch size 32 and 2xRTX 3090, gpu 0 has memory utilization of 14Gb, gpu 1 - 9gb. I've subtracted ubuntu's gpu usage on gpu 0 of 1gb. Why is that? 

I shall also try increasing batch size to 50 or so.
