### ISSUE TITLE
How to improve multilingual singing voice conversion?

### ISSUE THREAD

**Issue by MMMMichaelzhang** [yl4579/StarGANv2-VC#48]
The performance of speaking conversion is good, and the singing conversion  is not ideal. If I do singing voice conversion, can you teach me how to use hifigan, hififan also has a pre-model with the same parameters. Do you have any plans to upgrade the singing conversion next?

**Comment by yl4579** [comment]
Sorry for the late reply. I was pretty busy at the end of my semester. I'm interested in singing conversion with the same architecture, especially with Hifi-GAN. Actually, I already have some idea of how to improve the results. Hifi-GAN does significantly improve the results especially if you fine-tune it. The pre-trained Hifi-GAN likely won't work because the preprocessing is different. I will make my pre-trained HifiGAN available soon with the same preprocessing as this repo.

**Comment by MMMMichaelzhang** [comment]
The pretrained model's preprocessing is different,does it work ?

**Comment by skol101** [comment]
pretrained hifigan model:
24k | 80-7600 | 2048 / 300 / 1200

my StarGANv2 config preprocess params
```
preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
```

**Comment by skol101** [comment]
Actually after fine tuning for 50k steps from pretrained model I realised something amiss and decided to train Hifigan from the scratch just on my dataset.

**Comment by MMMMichaelzhang** [comment]
What changes have you made to train hifigan, such as config, and the proprecessing of hifigan? @skol101

**Comment by Kreevoz** [comment]
Guys, it would be best if you'd discuss matters that are about the vocoder training on the appropriate repo, which is https://github.com/kan-bayashi/ParallelWaveGAN and not repurpose closed issues for this. Or you know, discord each other.

Regarding preprocessing changes you can read some of the older issues such as #8 as this is a question that cropped up a few times.
