### ISSUE TITLE
Questions about Style diversification loss

### ISSUE THREAD

**Issue by Chevalier1024** [yl4579/StarGANv2-VC#50]
Thanks for your outstanding work! I have one question about the style diversification loss.  The style diversification loss is maximized to enforce the generator to generate different samples with different style codes.  However, the two refenences are same speakers that say different words. so should we minimize the style diversification loss to generate similar samples with same style?

**Comment by yl4579** [comment]
The idea is to maximize the differences so that any given two different references would produce different results. Some references might be so close to each other that their loss is very low after convergence, while other references are far away from each other so their loss super is high. The optimizer will take care of it and find the optimal solution.
