### ISSUE TITLE
about high samplerate training

### ISSUE THREAD

**Issue by MMMMichaelzhang** [yl4579/StarGANv2-VC#53]
I want to retrain vocoder for higher samplerate,do you have plan to update the vocoder training ?how about the vocoder preprocessing?

**Comment by Kreevoz** [comment]
Since you now have access to the training code for the ASR and F0 models, you can replace the preprocessing with whatever you like and train a vocoder with that too - you can adjust the preprocessing code of the PWG repo as you see fit. 
But you'd have to train all models from scratch with your new settings.

**Comment by MMMMichaelzhang** [comment]
Can you provide the preprocess.py for PWG training?Thank you very much! @Kreevoz
