### ISSUE TITLE
Live inference on windows

### ISSUE THREAD

**Issue by Chopin68** [yl4579/StarGANv2-VC#62]
Great production! For the live implementation of reasoning, is there any detailed code? I have tried it, but unfortunately, I still lack some experience in it. Any help will be appreciated.

**Comment by MaxGodTier** [comment]
Maybe @Pathos0925 https://github.com/yl4579/StarGANv2-VC/issues/15 would be willing to share the code, I'd be interested in that as well.

**Comment by Microgorath** [comment]
@Chopin68 @MaxGodTier Hey, I made a live inference implementation that processes microphone input and plays back the converted audio on my fork that works reasonably well. I'm new to computer audio, so the code needs some improvements. Let me know if you have any issues or suggestions! [Link to code](https://github.com/Microgorath/StarGANv2-VC-Live-Inference/blob/main/liveinference.py)

**Comment by Chopin68** [comment]
@Microgorath It's too awesome! Thank you very much for your reasoning implementation. You even made a sound card support. The effect is very good!

**Comment by Chopin68** [comment]
@Microgorath You may be interested in this [repo.](https://github.com/zhaohui8969/VST_NetProcess-) It is a vst plug-in that can work on DAW and perform real-time voice conversion based on [](https://github.com/bshall/soft-vc)

**Comment by Chopin68** [comment]
@MaxGodTier Can you provide me with your contact information? I think we can exchange and learn

**Comment by shuzubgul** [comment]
Hello, I am working on deep noise suppression algorithms for real time audio noise suppression in live audio call under the window of 10/20ms data chunk from microphone. Can you suggest if I should use the StarGan for the same use case for real time voice conversion given the input data is 10/20ms, please guide.

**Comment by Microgorath** [comment]
My implementation used the noisereduce python module and could only get down to around 50 ms chunks without sounding choppy. My method converts the past 1 second or so along with the new chunk then splices it back down to the size of the chunk and blends it with the previous converted chunks to prevent clicking from mismatched wave endpoints. 
I believe that was a big issue for me, the wave of the previous chunk endpoint will not match with the current chunk's start point, aka they are out of phase with eachother. To illustrate what I mean, record yourself saying the same word twice in audacity and then try to splice them together seamlessly with the first half of one and the second half of the other. You will hear a pop where the waves merge due to them not lining up, unless you blend them together with a crossfade. My crossfade was around 16 ms long to remove the pops between conversion chunks, so I'm not sure how you would go about doing the entire chunk in less than that using my method.
