### ISSUE TITLE
many-to-one question

### ISSUE THREAD

**Issue by 1nlplearner** [yl4579/StarGANv2-VC#76]
hello, i am a beginner, if i train a many-to-one vc model, like 200 speakers to one, what modifications do I need to make, and if it can improve the similarity with the target speaker
thanks

**Comment by 1nlplearner** [comment]
how to set Discriminator to solve few target speakers but a lot of source speakers

**Comment by yl4579** [comment]
Many-to-many already includes one-to-many, so if you train your model in the many-to-many manner it will work for one-to-many automatically. However, if you want to speed up the training to only have a single target speaker because you don't care about other speakers in your dataset, you may just modify [meldataset.py](https://github.com/yl4579/StarGANv2-VC/blob/main/meldataset.py#L62) to only return your target speaker as the reference.
